### ISSUE TITLE
tab group menu buttons

### ISSUE THREAD

**Issue by JaimeStill** [JaimeStill/offline-platform#17]
Attaching a `matMenu` to an `<a mat-tab-link ...>` results in change detection errors in the console. The desired behavior is to instead override the styling of `<a mat-button ...>`  to match an `<a mat-tab link. ...>` when it is attached to a tab group:

**layout.scss**  

```scss
nav.mat-tab-nav-bar a.mat-button {
  height: 48px;
  padding: 0 24px;
  opacity: .6;
  text-align: center;
  display: inline-flex;
  justify-content: center;
  align-items: center;
  white-space: nowrap;
  vertical-align: top;
  text-decoration: none;
  position: relative;
  overflow: hidden  
}
```

**example.html**

```html
<nav mat-tab-nav-bar>
  <!-- <a mat-tab-link> routes -->
  <span fxFlex></span>
  <a mat-button
     disableRipple
     [matMenuTriggerFor]="menu">
    Menu
  </a>
  <mat-menu #menu="matMenu">
    <!-- menu items -->
  </mat-menu>
</nav>
```
