### ISSUE TITLE
Non-standard Material color contrast values

### ISSUE THREAD

**Issue by JaimeStill** [JaimeStill/offline-platform#5]
**theme.scss**  

```scss
$light-success-contrast: mat.get-contrast-color-from-palette(mat.$green-palette, A700);
$light-info-contrast: mat.get-contrast-color-from-palette(mat.$light-blue-palette, A700);
$light-warning-contrast: mat.get-contrast-color-from-palette(mat.$amber-palette, A400);

@include style-theme(
    $light-theme,
    $light-success, $light-success-contrast,
    $light-info, $light-info-contrast,
    $light-warning, $light-warning-contrast
);

.app-dark {
    $dark-success-contrast: mat.get-contrast-color-from-palette(mat.$green-palette, A200);
    $dark-info-contrast: mat.get-contrast-color-from-palette(mat.$light-blue-palette, A200);
    $dark-warning-contrast: mat.get-contrast-color-from-palette(mat.$amber-palette, A200);

    @include style-theme(
        $dark-theme,
        $dark-success, $dark-success-contrast,
        $dark-info, $dark-info-contrast,
        $dark-warning, $dark-warning-contrast
    );
}
```

**style.scss**  

```scss
@mixin style-theme($theme, $success, $success-contrast, $info, $info-contrast, $warning, $warning-contrast) {
    .background-success {
        background-color: $success!important;
        color: $success-contrast!important;
    }

    .background-info{
        background-color: $info!important;
        color: $info-contrast!important;
    }

    .background-warning {
        background-color: $warning!important;
        color: $warning-contrast!important;
    }
}
````
